package cn.npnt.tiaps.entity;

// Generated 2011-12-19 22:17:45 by Hibernate Tools 3.4.0.CR1

/**
 * Criterion generated by hbm2java
 */
public class Criterion implements java.io.Serializable {

	private long id;
	private String category;
	private String title;
	private short hotter;

	public Criterion() {
	}

	public Criterion(String category, String title, short hotter) {
		this.category = category;
		this.title = title;
		this.hotter = hotter;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public short getHotter() {
		return this.hotter;
	}

	public void setHotter(short hotter) {
		this.hotter = hotter;
	}

}
