package cn.npnt.tiaps.entity;

// Generated 2011-12-19 22:17:45 by Hibernate Tools 3.4.0.CR1

/**
 * LookStatistic generated by hbm2java
 */
public class LookStatistic implements java.io.Serializable {

	private Long id;
	private Look look;
	private int repostCount;
	private int reportAbuse;
	private Integer vistedCount;
	private Integer favoritedCount;
	private Byte verdict;
	private Integer nominal;
	private Integer hotter;

	public LookStatistic() {
		this.vistedCount = 0;
		this.favoritedCount = 0;
		this.nominal = 0;
		this.hotter = 0;
		this.verdict = -1;//缺省为等待裁决
	}

	public LookStatistic(Look look, int repostCount, int reportAbuse) {
		this.look = look;
		this.repostCount = repostCount;
		this.reportAbuse = reportAbuse;
	}

	public LookStatistic(Look look, int repostCount, int reportAbuse,
			Integer vistedCount, Integer favoritedCount, Byte verdict,
			Integer nominal, Integer hotter) {
		this.look = look;
		this.repostCount = repostCount;
		this.reportAbuse = reportAbuse;
		this.vistedCount = vistedCount;
		this.favoritedCount = favoritedCount;
		this.verdict = verdict;
		this.nominal = nominal;
		this.hotter = hotter;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Look getLook() {
		return this.look;
	}

	public void setLook(Look look) {
		this.look = look;
	}

	public int getRepostCount() {
		return this.repostCount;
	}

	public void setRepostCount(int repostCount) {
		this.repostCount = repostCount;
	}

	public int getReportAbuse() {
		return this.reportAbuse;
	}

	public void setReportAbuse(int reportAbuse) {
		this.reportAbuse = reportAbuse;
	}

	public Integer getVistedCount() {
		return this.vistedCount;
	}

	public void setVistedCount(Integer vistedCount) {
		this.vistedCount = vistedCount;
	}

	public Integer getFavoritedCount() {
		return this.favoritedCount;
	}

	public void setFavoritedCount(Integer favoritedCount) {
		this.favoritedCount = favoritedCount;
	}

	public Byte getVerdict() {
		return this.verdict;
	}

	public void setVerdict(Byte verdict) {
		this.verdict = verdict;
	}

	public Integer getNominal() {
		return this.nominal;
	}

	public void setNominal(Integer nominal) {
		this.nominal = nominal;
	}

	public Integer getHotter() {
		return this.hotter;
	}

	public void setHotter(Integer hotter) {
		this.hotter = hotter;
	}

}
