package cn.npnt.tiaps.entity;

// Generated 2011-12-19 22:17:45 by Hibernate Tools 3.4.0.CR1

/**
 * LookTrend generated by hbm2java
 */
public class LookTrend implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private int version;
	private Look look;
	private Trend trend;

	public LookTrend() {
	}

	public LookTrend(Look look, Trend trend) {
		this.version = 1;
		this.look = look;
		this.trend = trend;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public int getVersion() {
		return version;
	}
	public void setVersion(int version) {
		this.version = version;
	}
	public Look getLook() {
		return look;
	}
	public void setLook(Look look) {
		this.look = look;
	}
	public Trend getTrend() {
		return trend;
	}
	public void setTrend(Trend trend) {
		this.trend = trend;
	}
}
