package cn.npnt.tiaps.entity;

// Generated 2011-12-19 22:17:45 by Hibernate Tools 3.4.0.CR1

/**
 * Mention generated by hbm2java
 */
public class Mention implements java.io.Serializable {

	private Long id;
	private int version;
	private User user;
	private Look look;
	private Boolean informed;

	public Mention() {
	}

	public Mention(User user, Look look) {
		this.user = user;
		this.look = look;
	}

	public Mention(User user, Look look, Boolean informed) {
		this.user = user;
		this.look = look;
		this.informed = informed;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Look getLook() {
		return this.look;
	}

	public void setLook(Look look) {
		this.look = look;
	}

	public Boolean getInformed() {
		return this.informed;
	}

	public void setInformed(Boolean informed) {
		this.informed = informed;
	}

}
