package cn.npnt.tiaps.entity;

// Generated 2011-12-16 0:03:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Style generated by hbm2java
 */
public class Style implements java.io.Serializable {

	private long id;
	private int version;
	private Date updateTime;
	private Boolean deleted;
	private String title;
	private Integer index;

	public Style() {
	}

	public Style(long id) {
		this.id = id;
	}

	public Style(long id, Date updateTime, Boolean deleted, String title,
			Integer index) {
		this.id = id;
		this.updateTime = updateTime;
		this.deleted = deleted;
		this.title = title;
		this.index = index;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Integer getIndex() {
		return this.index;
	}

	public void setIndex(Integer index) {
		this.index = index;
	}

}
