package cn.npnt.tiaps.entity;

// Generated 2012-2-15 20:28:47 by Hibernate Tools 3.4.0.CR1

/**
 * TimelineId generated by hbm2java
 */
public class TimelineId implements java.io.Serializable {

	private long userId;
	private long lookId;

	public TimelineId() {
	}

	public TimelineId(long userId, long lookId) {
		this.userId = userId;
		this.lookId = lookId;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public long getLookId() {
		return this.lookId;
	}

	public void setLookId(long lookId) {
		this.lookId = lookId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TimelineId))
			return false;
		TimelineId castOther = (TimelineId) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getLookId() == castOther.getLookId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUserId();
		result = 37 * result + (int) this.getLookId();
		return result;
	}

}
