package cn.npnt.tiaps.entity;

// Generated 2011-12-16 0:03:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.Set;

/**
 * Trend generated by hbm2java
 */
public class Trend implements java.io.Serializable {

	private long id;
	private int version;
	private boolean deleted;
	private String title;
	private Date createTime;
	private Set<LookTrend> lookTrends;

	public Trend() {
	}

	public Trend(long id, boolean deleted, String title, Date createTime) {
		this.id = id;
		this.deleted = deleted;
		this.title = title;
		this.createTime = createTime;
	}
	public long getId() {
		return this.id;
	}
	public void setId(long id) {
		this.id = id;
	}
	public int getVersion() {
		return this.version;
	}
	public void setVersion(int version) {
		this.version = version;
	}
	public boolean isDeleted() {
		return this.deleted;
	}
	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}
	public String getTitle() {
		return this.title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Set<LookTrend> getLookTrends() {
		return this.lookTrends;
	}

	public void setLookTrends(Set<LookTrend> lookTrends) {
		this.lookTrends = lookTrends;
	}

}
