package cn.npnt.tiaps.entity;

import java.util.Date;

// Generated 2011-12-19 22:17:45 by Hibernate Tools 3.4.0.CR1

/**
 * Vote generated by hbm2java
 */
public class Vote implements java.io.Serializable {

	private Long id;
	private int version;
	private User user;
	private Look look;
	private Date createTime;
	private Byte photoIndex;

	public Vote() {
	}

	public Vote(User user, Date createTime) {
		this.user = user;
		this.createTime = createTime;
	}

	public Vote(User user, Look look, Date createTime, Byte photoIndex) {
		this.user = user;
		this.look = look;
		this.createTime = createTime;
		this.photoIndex = photoIndex;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Look getLook() {
		return this.look;
	}

	public void setLook(Look look) {
		this.look = look;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Byte getPhotoIndex() {
		return this.photoIndex;
	}

	public void setPhotoIndex(Byte photoIndex) {
		this.photoIndex = photoIndex;
	}

}
