package cn.npnt.tiaps.entity;

// Generated 2011-12-22 23:49:30 by Hibernate Tools 3.4.0.CR1

/**
 * WearBrand generated by hbm2java
 */
public class WearBrand implements java.io.Serializable {

	private long id;
	private Photo photo;
	private String brand;
	private String clothing;

	public WearBrand() {
	}

	public WearBrand(Photo photo, String brand, String clothing) {
		this.photo = photo;
		this.brand = brand;
		this.clothing = clothing;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Photo getPhoto() {
		return this.photo;
	}

	public void setPhoto(Photo photo) {
		this.photo = photo;
	}

	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public String getClothing() {
		return this.clothing;
	}

	public void setClothing(String clothing) {
		this.clothing = clothing;
	}

}
